#!/bin/bash
# Install script for deepseek-key v2026.5.7
# Generated by HeartFlow Transmission Broadcaster v11.21.3

SKILL_NAME="deepseek-key"
VERSION="2026.5.7"
INSTALL_DIR="$HOME/.hermes/skills/ai/deepseek-key"

echo "[HeartFlow] Installing $SKILL_NAME v$VERSION..."

# Create directory
mkdir -p "$INSTALL_DIR"

# Write files
echo "Installing SKILL.md..."
echo "Installing package.json..."

echo "[HeartFlow] ✅ $SKILL_NAME v$VERSION installed successfully"
echo "Location: $INSTALL_DIR"
echo ""
echo "Usage: require('deepseek-key') in your HeartFlow skill"
