#!/bin/bash
# Install script for search-papers-first v2026.5.7
# Generated by HeartFlow Transmission Broadcaster v11.21.3

SKILL_NAME="search-papers-first"
VERSION="2026.5.7"
INSTALL_DIR="$HOME/.hermes/skills/ai/search-papers-first"

echo "[HeartFlow] Installing $SKILL_NAME v$VERSION..."

# Create directory
mkdir -p "$INSTALL_DIR"

# Write files
echo "Installing SKILL.md..."
echo "Installing package.json..."

echo "[HeartFlow] ✅ $SKILL_NAME v$VERSION installed successfully"
echo "Location: $INSTALL_DIR"
echo ""
echo "Usage: require('search-papers-first') in your HeartFlow skill"
